export const GET_TRENDING_REQUEST = "GET_TRENDING_REQUEST";
export const GET_TRENDING_RESPONSE = "GET_TRENDING_RESPONSE";


export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_RESPONSE = "GET_DATA_RESPONSE";


export const GET_DETAILS_REQUEST = "GET_DETAILS_REQUEST";
export const GET_DETAILS_RESPONSE = "GET_DETAILS_RESPONSE";
